### ISSUE TITLE
Models.py is missing

### ISSUE THREAD

**Issue by Aitical** [OFA-Sys/diffusion-deploy#1]
Nice work! Thanks for sharing your deploying code.

For gpu tensorrt, models.py containing CLIP, VAE, and UNet is missing.  The models.py from the official Tensorrt GitHub did not work. 

Here, requiring the models.py.

**Comment by lexuszhi1990** [comment]
+1

**Comment by geekinglcq** [comment]
Hi, thx for your attention. You could refer to `diffusers` to obtain the models used here. 
https://huggingface.co/docs/diffusers/index
